### ISSUE TITLE
Network centroid definition

### ISSUE THREAD

**Issue by victoris93** [rb643/GradientDispersion#2]
Hi there!

I am trying to implement your dispersion in Python. Having a minimal knowledge of Matlab, I was just wondering if you could confirm/refute my understanding of how you defined network centroids (a.k.a "centre of gravity"?) in `camcan_functional_gradients.m`. Given the snippet below, I reckon that the centroid coordinates of network X in the 3D gradient space are *the median values of gradients 1-3 of network X*. Is that so?
A huge thanks in advance!

```
yeo_cog = np.zeros((num_subjects, 3, num_networks))
yeo_netSSD = np.zeros((num_subjects, num_networks))
mdl_yeo = np.zeros((num_coefficients, num_coefficients, num_networks))

for n in range(1, num_networks + 1):
    netNodes = np.where(yeo_parc == n)[0]
    group_yeo_cog = np.median(group_grad[netNodes], axis=0)
    
    for s in range(num_subjects):
        yeo_cog[s, :, n - 1] = np.median(G1[netNodes, :3, s], axis=0)
        yeo_cog_dist = np.linalg.norm(group_yeo_cog - yeo_cog[s, :, n - 1])
        
        dist_to_centre = np.linalg.norm(G1[netNodes, :3, s] - yeo_cog[s, :, n - 1], axis=1)
        yeo_netSSD[s, n - 1] = np.sum(dist_to_centre ** 2)
```

**Comment by rb643** [comment]
Hi Victoria,

Yes that is correct.

Cheers,

Richard
